include \Masm64\Include\1394bus.inc
includelib \Masm64\Lib\1394bus.lib
include \Masm64\Include\acledit.inc
includelib \Masm64\Lib\acledit.lib
include \Masm64\Include\aclui.inc
includelib \Masm64\Lib\aclui.lib
include \Masm64\Include\activeds.inc
includelib \Masm64\Lib\activeds.lib
include \Masm64\Include\adptif.inc
includelib \Masm64\Lib\adptif.lib
include \Masm64\Include\advapi32.inc
includelib \Masm64\Lib\advapi32.lib
include \Masm64\Include\advapip.inc
includelib \Masm64\Lib\advapip.lib
include \Masm64\Include\advpack.inc
includelib \Masm64\Lib\advpack.lib
include \Masm64\Include\appmgmts.inc
includelib \Masm64\Lib\appmgmts.lib
include \Masm64\Include\arbiter.inc
includelib \Masm64\Lib\arbiter.lib
include \Masm64\Include\authz.inc
includelib \Masm64\Lib\authz.lib
include \Masm64\Include\basesrv.inc
includelib \Masm64\Lib\basesrv.lib
include \Masm64\Include\batmeter.inc
includelib \Masm64\Lib\batmeter.lib
include \Masm64\Include\battc.inc
includelib \Masm64\Lib\battc.lib
include \Masm64\Include\bdasup.inc
includelib \Masm64\Lib\bdasup.lib
include \Masm64\Include\bufferoverflow.inc
includelib \Masm64\Lib\bufferoverflow.lib
include \Masm64\Include\bufferoverflowgdi.inc
includelib \Masm64\Lib\bufferoverflowgdi.lib
include \Masm64\Include\bufferoverflowk.inc
includelib \Masm64\Lib\bufferoverflowk.lib
include \Masm64\Include\bufferoverflowu.inc
includelib \Masm64\Lib\bufferoverflowu.lib
include \Masm64\Include\cabinet.inc
includelib \Masm64\Lib\cabinet.lib
include \Masm64\Include\ccfapi32.inc
includelib \Masm64\Lib\ccfapi32.lib
include \Masm64\Include\certadm.inc
includelib \Masm64\Lib\certadm.lib
include \Masm64\Include\certidl.inc
includelib \Masm64\Lib\certidl.lib
include \Masm64\Include\cfgmgr.inc
includelib \Masm64\Lib\cfgmgr.lib
include \Masm64\Include\cfgmgr32.inc
includelib \Masm64\Lib\cfgmgr32.lib
include \Masm64\Include\classpnp.inc
includelib \Masm64\Lib\classpnp.lib
include \Masm64\Include\clusapi.inc
includelib \Masm64\Lib\clusapi.lib
include \Masm64\Include\comctl32.inc
includelib \Masm64\Lib\comctl32.lib
include \Masm64\Include\comdlg32.inc
includelib \Masm64\Lib\comdlg32.lib
include \Masm64\Include\compstui.inc
includelib \Masm64\Lib\compstui.lib
include \Masm64\Include\comsvcs.inc
includelib \Masm64\Lib\comsvcs.lib
include \Masm64\Include\credui.inc
includelib \Masm64\Lib\credui.lib
include \Masm64\Include\crypt32.inc
includelib \Masm64\Lib\crypt32.lib
include \Masm64\Include\cryptdll.inc
includelib \Masm64\Lib\cryptdll.lib
include \Masm64\Include\cryptnet.inc
includelib \Masm64\Lib\cryptnet.lib
include \Masm64\Include\cryptui.inc
includelib \Masm64\Lib\cryptui.lib
include \Masm64\Include\cscdll.inc
includelib \Masm64\Lib\cscdll.lib
include \Masm64\Include\csq.inc
includelib \Masm64\Lib\csq.lib
include \Masm64\Include\d3d8.inc
includelib \Masm64\Lib\d3d8.lib
include \Masm64\Include\d3dpmesh.inc
includelib \Masm64\Lib\d3dpmesh.lib
include \Masm64\Include\d3dx8d.inc
includelib \Masm64\Lib\d3dx8d.lib
include \Masm64\Include\d3dxof.inc
includelib \Masm64\Lib\d3dxof.lib
include \Masm64\Include\ddraw.inc
includelib \Masm64\Lib\ddraw.lib
include \Masm64\Include\delayimp.inc
includelib \Masm64\Lib\delayimp.lib
include \Masm64\Include\devmgr.inc
includelib \Masm64\Lib\devmgr.lib
include \Masm64\Include\dflayout.inc
includelib \Masm64\Lib\dflayout.lib
include \Masm64\Include\dhcpcsvc.inc
includelib \Masm64\Lib\dhcpcsvc.lib
include \Masm64\Include\dinput.inc
includelib \Masm64\Lib\dinput.lib
include \Masm64\Include\dinput8.inc
includelib \Masm64\Lib\dinput8.lib
include \Masm64\Include\dlcapi.inc
includelib \Masm64\Lib\dlcapi.lib
include \Masm64\Include\dnsapi.inc
includelib \Masm64\Lib\dnsapi.lib
include \Masm64\Include\dnscrcli.inc
includelib \Masm64\Lib\dnscrcli.lib
include \Masm64\Include\dnslib.inc
includelib \Masm64\Lib\dnslib.lib
include \Masm64\Include\dnsperf.inc
includelib \Masm64\Lib\dnsperf.lib
include \Masm64\Include\dnsrpc.inc
includelib \Masm64\Lib\dnsrpc.lib
include \Masm64\Include\dnsrslvr.inc
includelib \Masm64\Lib\dnsrslvr.lib
include \Masm64\Include\dplayx.inc
includelib \Masm64\Lib\dplayx.lib
include \Masm64\Include\dpmodemx.inc
includelib \Masm64\Lib\dpmodemx.lib
include \Masm64\Include\dpwsockx.inc
includelib \Masm64\Lib\dpwsockx.lib
include \Masm64\Include\drmk.inc
includelib \Masm64\Lib\drmk.lib
include \Masm64\Include\dsound.inc
includelib \Masm64\Lib\dsound.lib
include \Masm64\Include\dsprop.inc
includelib \Masm64\Lib\dsprop.lib
include \Masm64\Include\dssec.inc
includelib \Masm64\Lib\dssec.lib
include \Masm64\Include\dsuiext.inc
includelib \Masm64\Lib\dsuiext.lib
include \Masm64\Include\dtchelp.inc
includelib \Masm64\Lib\dtchelp.lib
include \Masm64\Include\dxapi.inc
includelib \Masm64\Lib\dxapi.lib
include \Masm64\Include\elfapi.inc
includelib \Masm64\Lib\elfapi.lib
include \Masm64\Include\esent.inc
includelib \Masm64\Lib\esent.lib
include \Masm64\Include\excppkg.inc
includelib \Masm64\Lib\excppkg.lib
include \Masm64\Include\fci.inc
includelib \Masm64\Lib\fci.lib
include \Masm64\Include\fdi.inc
includelib \Masm64\Lib\fdi.lib
include \Masm64\Include\feclient.inc
includelib \Masm64\Lib\feclient.lib
include \Masm64\Include\framedyd.inc
includelib \Masm64\Lib\framedyd.lib
include \Masm64\Include\framedyn.inc
includelib \Masm64\Lib\framedyn.lib
include \Masm64\Include\gdi32.inc
includelib \Masm64\Lib\gdi32.lib
include \Masm64\Include\gdiplus.inc
includelib \Masm64\Lib\gdiplus.lib
include \Masm64\Include\glmf32.inc
includelib \Masm64\Lib\glmf32.lib
include \Masm64\Include\glu32.inc
includelib \Masm64\Lib\glu32.lib
include \Masm64\Include\gpedit.inc
includelib \Masm64\Lib\gpedit.lib
include \Masm64\Include\hal.inc
includelib \Masm64\Lib\hal.lib
include \Masm64\Include\hcaport.inc
includelib \Masm64\Lib\hcaport.lib
include \Masm64\Include\hid.inc
includelib \Masm64\Lib\hid.lib
include \Masm64\Include\hidclass.inc
includelib \Masm64\Lib\hidclass.lib
include \Masm64\Include\hidparse.inc
includelib \Masm64\Lib\hidparse.lib
include \Masm64\Include\hlink.inc
includelib \Masm64\Lib\hlink.lib
include \Masm64\Include\htmlhelp.inc
includelib \Masm64\Lib\htmlhelp.lib
include \Masm64\Include\iashlpr.inc
includelib \Masm64\Lib\iashlpr.lib
include \Masm64\Include\icm32.inc
includelib \Masm64\Lib\icm32.lib
include \Masm64\Include\icmui.inc
includelib \Masm64\Lib\icmui.lib
include \Masm64\Include\iesetup.inc
includelib \Masm64\Lib\iesetup.lib
include \Masm64\Include\imagehlp.inc
includelib \Masm64\Lib\imagehlp.lib
include \Masm64\Include\imgutil.inc
includelib \Masm64\Lib\imgutil.lib
include \Masm64\Include\imm32.inc
includelib \Masm64\Lib\imm32.lib
include \Masm64\Include\inseng.inc
includelib \Masm64\Lib\inseng.lib
include \Masm64\Include\iphlpapi.inc
includelib \Masm64\Lib\iphlpapi.lib
include \Masm64\Include\iprop.inc
includelib \Masm64\Lib\iprop.lib
include \Masm64\Include\kerbcli.inc
includelib \Masm64\Lib\kerbcli.lib
include \Masm64\Include\kernel32.inc
includelib \Masm64\Lib\kernel32.lib
include \Masm64\Include\kernl32p.inc
includelib \Masm64\Lib\kernl32p.lib
include \Masm64\Include\ks.inc
includelib \Masm64\Lib\ks.lib
include \Masm64\Include\ksecdd.inc
includelib \Masm64\Lib\ksecdd.lib
include \Masm64\Include\ksproxy.inc
includelib \Masm64\Lib\ksproxy.lib
include \Masm64\Include\ksuser.inc
includelib \Masm64\Lib\ksuser.lib
include \Masm64\Include\llsrpc.inc
includelib \Masm64\Lib\llsrpc.lib
include \Masm64\Include\loadperf.inc
includelib \Masm64\Lib\loadperf.lib
include \Masm64\Include\lsadll.inc
includelib \Masm64\Lib\lsadll.lib
include \Masm64\Include\lsasrv.inc
includelib \Masm64\Lib\lsasrv.lib
include \Masm64\Include\lsasrvd.inc
includelib \Masm64\Lib\lsasrvd.lib
include \Masm64\Include\lz32.inc
includelib \Masm64\Lib\lz32.lib
include \Masm64\Include\mapi32.inc
includelib \Masm64\Lib\mapi32.lib
include \Masm64\Include\mcd.inc
includelib \Masm64\Lib\mcd.lib
include \Masm64\Include\mcd32.inc
includelib \Masm64\Lib\mcd32.lib
include \Masm64\Include\mcdsrv32.inc
includelib \Masm64\Lib\mcdsrv32.lib
include \Masm64\Include\mciole32.inc
includelib \Masm64\Lib\mciole32.lib
include \Masm64\Include\mgmtapi.inc
includelib \Masm64\Lib\mgmtapi.lib
include \Masm64\Include\mmc.inc
includelib \Masm64\Lib\mmc.lib
include \Masm64\Include\mpr.inc
includelib \Masm64\Lib\mpr.lib
include \Masm64\Include\mprapi.inc
includelib \Masm64\Lib\mprapi.lib
include \Masm64\Include\mprsnap.inc
includelib \Masm64\Lib\mprsnap.lib
include \Masm64\Include\mqrt.inc
includelib \Masm64\Lib\mqrt.lib
include \Masm64\Include\msacm32.inc
includelib \Masm64\Lib\msacm32.lib
include \Masm64\Include\msasn1.inc
includelib \Masm64\Lib\msasn1.lib
include \Masm64\Include\mscms.inc
includelib \Masm64\Lib\mscms.lib
include \Masm64\Include\msdmo.inc
includelib \Masm64\Lib\msdmo.lib
include \Masm64\Include\msi.inc
includelib \Masm64\Lib\msi.lib
include \Masm64\Include\msimg32.inc
includelib \Masm64\Lib\msimg32.lib
include \Masm64\Include\mspbase.inc
includelib \Masm64\Lib\mspbase.lib
include \Masm64\Include\msports.inc
includelib \Masm64\Lib\msports.lib
include \Masm64\Include\msrating.inc
includelib \Masm64\Lib\msrating.lib
include \Masm64\Include\mstask.inc
includelib \Masm64\Lib\mstask.lib
include \Masm64\Include\msv1_0.inc
includelib \Masm64\Lib\msv1_0.lib
include \Masm64\Include\mswsock.inc
includelib \Masm64\Lib\mswsock.lib
include \Masm64\Include\mtx.inc
includelib \Masm64\Lib\mtx.lib
include \Masm64\Include\nddeapi.inc
includelib \Masm64\Lib\nddeapi.lib
include \Masm64\Include\ndis.inc
includelib \Masm64\Lib\ndis.lib
include \Masm64\Include\netapi32.inc
includelib \Masm64\Lib\netapi32.lib
include \Masm64\Include\netlib.inc
includelib \Masm64\Lib\netlib.lib
include \Masm64\Include\netrap.inc
includelib \Masm64\Lib\netrap.lib
include \Masm64\Include\netui2.inc
includelib \Masm64\Lib\netui2.lib
include \Masm64\Include\newdev.inc
includelib \Masm64\Lib\newdev.lib
include \Masm64\Include\nmapi.inc
includelib \Masm64\Lib\nmapi.lib
include \Masm64\Include\nmsupp.inc
includelib \Masm64\Lib\nmsupp.lib
include \Masm64\Include\npptools.inc
includelib \Masm64\Lib\npptools.lib
include \Masm64\Include\nt.inc
includelib \Masm64\Lib\nt.lib
include \Masm64\Include\ntdll.inc
includelib \Masm64\Lib\ntdll.lib
include \Masm64\Include\ntdsa.inc
includelib \Masm64\Lib\ntdsa.lib
include \Masm64\Include\ntdsapi.inc
includelib \Masm64\Lib\ntdsapi.lib
include \Masm64\Include\ntdsatq.inc
includelib \Masm64\Lib\ntdsatq.lib
include \Masm64\Include\ntdsbcli.inc
includelib \Masm64\Lib\ntdsbcli.lib
include \Masm64\Include\ntdsetup.inc
includelib \Masm64\Lib\ntdsetup.lib
include \Masm64\Include\ntfrsapi.inc
includelib \Masm64\Lib\ntfrsapi.lib
include \Masm64\Include\ntlanman.inc
includelib \Masm64\Lib\ntlanman.lib
include \Masm64\Include\ntlanui.inc
includelib \Masm64\Lib\ntlanui.lib
include \Masm64\Include\ntmarta.inc
includelib \Masm64\Lib\ntmarta.lib
include \Masm64\Include\ntmsapi.inc
includelib \Masm64\Lib\ntmsapi.lib
include \Masm64\Include\ntoskrnl.inc
includelib \Masm64\Lib\ntoskrnl.lib
include \Masm64\Include\ntquery.inc
includelib \Masm64\Lib\ntquery.lib
include \Masm64\Include\ntstrsafe.inc
includelib \Masm64\Lib\ntstrsafe.lib
include \Masm64\Include\nwsaplib.inc
includelib \Masm64\Lib\nwsaplib.lib
include \Masm64\Include\odbc32.inc
includelib \Masm64\Lib\odbc32.lib
include \Masm64\Include\odbccp32.inc
includelib \Masm64\Lib\odbccp32.lib
include \Masm64\Include\ole32.inc
includelib \Masm64\Lib\ole32.lib
include \Masm64\Include\oleacc.inc
includelib \Masm64\Lib\oleacc.lib
include \Masm64\Include\oleaut32.inc
includelib \Masm64\Lib\oleaut32.lib
include \Masm64\Include\olecli32.inc
includelib \Masm64\Lib\olecli32.lib
include \Masm64\Include\oledlg.inc
includelib \Masm64\Lib\oledlg.lib
include \Masm64\Include\olepro32.inc
includelib \Masm64\Lib\olepro32.lib
include \Masm64\Include\olesvr32.inc
includelib \Masm64\Lib\olesvr32.lib
include \Masm64\Include\opengl32.inc
includelib \Masm64\Lib\opengl32.lib
include \Masm64\Include\oprghdlr.inc
includelib \Masm64\Lib\oprghdlr.lib
include \Masm64\Include\parser.inc
includelib \Masm64\Lib\parser.lib
include \Masm64\Include\pciidex.inc
includelib \Masm64\Lib\pciidex.lib
include \Masm64\Include\pdh.inc
includelib \Masm64\Lib\pdh.lib
include \Masm64\Include\portcls.inc
includelib \Masm64\Lib\portcls.lib
include \Masm64\Include\powrprof.inc
includelib \Masm64\Lib\powrprof.lib
include \Masm64\Include\psapi.inc
includelib \Masm64\Lib\psapi.lib
include \Masm64\Include\ptilink.inc
includelib \Masm64\Lib\ptilink.lib
include \Masm64\Include\qosname.inc
includelib \Masm64\Lib\qosname.lib
include \Masm64\Include\quartz.inc
includelib \Masm64\Lib\quartz.lib
include \Masm64\Include\query.inc
includelib \Masm64\Lib\query.lib
include \Masm64\Include\randlibk.inc
includelib \Masm64\Lib\randlibk.lib
include \Masm64\Include\rasapi32.inc
includelib \Masm64\Lib\rasapi32.lib
include \Masm64\Include\rasdlg.inc
includelib \Masm64\Lib\rasdlg.lib
include \Masm64\Include\rassapi.inc
includelib \Masm64\Lib\rassapi.lib
include \Masm64\Include\resutils.inc
includelib \Masm64\Lib\resutils.lib
include \Masm64\Include\rpcexts.inc
includelib \Masm64\Lib\rpcexts.lib
include \Masm64\Include\rpcns4.inc
includelib \Masm64\Lib\rpcns4.lib
include \Masm64\Include\rpcproxy.inc
includelib \Masm64\Lib\rpcproxy.lib
include \Masm64\Include\rpcrt4.inc
includelib \Masm64\Lib\rpcrt4.lib
include \Masm64\Include\rpcutil.inc
includelib \Masm64\Lib\rpcutil.lib
include \Masm64\Include\rtm.inc
includelib \Masm64\Lib\rtm.lib
include \Masm64\Include\rtutils.inc
includelib \Masm64\Lib\rtutils.lib
include \Masm64\Include\rxapi.inc
includelib \Masm64\Lib\rxapi.lib
include \Masm64\Include\rxcommon.inc
includelib \Masm64\Lib\rxcommon.lib
include \Masm64\Include\samlib.inc
includelib \Masm64\Lib\samlib.lib
include \Masm64\Include\samsrv.inc
includelib \Masm64\Lib\samsrv.lib
include \Masm64\Include\scarddlg.inc
includelib \Masm64\Lib\scarddlg.lib
include \Masm64\Include\scecli.inc
includelib \Masm64\Lib\scecli.lib
include \Masm64\Include\scesrv.inc
includelib \Masm64\Lib\scesrv.lib
include \Masm64\Include\schannel.inc
includelib \Masm64\Lib\schannel.lib
include \Masm64\Include\sclogon.inc
includelib \Masm64\Lib\sclogon.lib
include \Masm64\Include\scrnsave.inc
includelib \Masm64\Lib\scrnsave.lib
include \Masm64\Include\scrnsavw.inc
includelib \Masm64\Lib\scrnsavw.lib
include \Masm64\Include\scsiport.inc
includelib \Masm64\Lib\scsiport.lib
include \Masm64\Include\scsiwmi.inc
includelib \Masm64\Lib\scsiwmi.lib
include \Masm64\Include\sdbus.inc
includelib \Masm64\Lib\sdbus.lib
include \Masm64\Include\secur32.inc
includelib \Masm64\Lib\secur32.lib
include \Masm64\Include\security.inc
includelib \Masm64\Lib\security.lib
include \Masm64\Include\sens.inc
includelib \Masm64\Lib\sens.lib
include \Masm64\Include\sensapi.inc
includelib \Masm64\Lib\sensapi.lib
include \Masm64\Include\setupapi.inc
includelib \Masm64\Lib\setupapi.lib
include \Masm64\Include\setupexts.inc
includelib \Masm64\Lib\setupexts.lib
include \Masm64\Include\sfc.inc
includelib \Masm64\Lib\sfc.lib
include \Masm64\Include\sfcfiles.inc
includelib \Masm64\Lib\sfcfiles.lib
include \Masm64\Include\shell32.inc
includelib \Masm64\Lib\shell32.lib
include \Masm64\Include\shfolder.inc
includelib \Masm64\Lib\shfolder.lib
include \Masm64\Include\shlwapi.inc
includelib \Masm64\Lib\shlwapi.lib
include \Masm64\Include\sisbkup.inc
includelib \Masm64\Lib\sisbkup.lib
include \Masm64\Include\smbtrsup.inc
includelib \Masm64\Lib\smbtrsup.lib
include \Masm64\Include\smclib.inc
includelib \Masm64\Lib\smclib.lib
include \Masm64\Include\snmpapi.inc
includelib \Masm64\Lib\snmpapi.lib
include \Masm64\Include\spoolss.inc
includelib \Masm64\Lib\spoolss.lib
include \Masm64\Include\sporder.inc
includelib \Masm64\Lib\sporder.lib
include \Masm64\Include\ssdpapi.inc
includelib \Masm64\Lib\ssdpapi.lib
include \Masm64\Include\stdunk.inc
includelib \Masm64\Lib\stdunk.lib
include \Masm64\Include\sti.inc
includelib \Masm64\Lib\sti.lib
include \Masm64\Include\storport.inc
includelib \Masm64\Lib\storport.lib
include \Masm64\Include\stream.inc
includelib \Masm64\Lib\stream.lib
include \Masm64\Include\syssetup.inc
includelib \Masm64\Lib\syssetup.lib
include \Masm64\Include\tape.inc
includelib \Masm64\Lib\tape.lib
include \Masm64\Include\tapi32.inc
includelib \Masm64\Lib\tapi32.lib
include \Masm64\Include\tapi32l.inc
includelib \Masm64\Lib\tapi32l.lib
include \Masm64\Include\tcpip.inc
includelib \Masm64\Lib\tcpip.lib
include \Masm64\Include\tcpip6.inc
includelib \Masm64\Lib\tcpip6.lib
include \Masm64\Include\tdi.inc
includelib \Masm64\Lib\tdi.lib
include \Masm64\Include\traffic.inc
includelib \Masm64\Lib\traffic.lib
include \Masm64\Include\tsec.inc
includelib \Masm64\Lib\tsec.lib
include \Masm64\Include\twain_32.inc
includelib \Masm64\Lib\twain_32.lib
include \Masm64\Include\umpdddi.inc
includelib \Masm64\Lib\umpdddi.lib
include \Masm64\Include\umpnplib.inc
includelib \Masm64\Lib\umpnplib.lib
include \Masm64\Include\urlmon.inc
includelib \Masm64\Lib\urlmon.lib
include \Masm64\Include\usbcamd.inc
includelib \Masm64\Lib\usbcamd.lib
include \Masm64\Include\usbcamd2.inc
includelib \Masm64\Lib\usbcamd2.lib
include \Masm64\Include\usbd.inc
includelib \Masm64\Lib\usbd.lib
include \Masm64\Include\user32.inc
includelib \Masm64\Lib\user32.lib
include \Masm64\Include\userenv.inc
includelib \Masm64\Lib\userenv.lib
include \Masm64\Include\usp10.inc
includelib \Masm64\Lib\usp10.lib
include \Masm64\Include\uxtheme.inc
includelib \Masm64\Lib\uxtheme.lib
include \Masm64\Include\vccomsup.inc
includelib \Masm64\Lib\vccomsup.lib
include \Masm64\Include\version.inc
includelib \Masm64\Lib\version.lib
include \Masm64\Include\vfw32.inc
includelib \Masm64\Lib\vfw32.lib
include \Masm64\Include\videoprt.inc
includelib \Masm64\Lib\videoprt.lib
include \Masm64\Include\wdm.inc
includelib \Masm64\Lib\wdm.lib
include \Masm64\Include\wdmsec.inc
includelib \Masm64\Lib\wdmsec.lib
include \Masm64\Include\wiaservc.inc
includelib \Masm64\Lib\wiaservc.lib
include \Masm64\Include\wiautil.inc
includelib \Masm64\Lib\wiautil.lib
include \Masm64\Include\win32k.inc
includelib \Masm64\Lib\win32k.lib
include \Masm64\Include\winfax.inc
includelib \Masm64\Lib\winfax.lib
include \Masm64\Include\wininet.inc
includelib \Masm64\Lib\wininet.lib
include \Masm64\Include\winmm.inc
includelib \Masm64\Lib\winmm.lib
include \Masm64\Include\winppi.inc
includelib \Masm64\Lib\winppi.lib
include \Masm64\Include\winscard.inc
includelib \Masm64\Lib\winscard.lib
include \Masm64\Include\winspool.inc
includelib \Masm64\Lib\winspool.lib
include \Masm64\Include\winsta.inc
includelib \Masm64\Lib\winsta.lib
include \Masm64\Include\winstrm.inc
includelib \Masm64\Lib\winstrm.lib
include \Masm64\Include\wintrust.inc
includelib \Masm64\Lib\wintrust.lib
include \Masm64\Include\wmilib.inc
includelib \Masm64\Lib\wmilib.lib
include \Masm64\Include\wmip.inc
includelib \Masm64\Lib\wmip.lib
include \Masm64\Include\wmvcore.inc
includelib \Masm64\Lib\wmvcore.lib
include \Masm64\Include\ws2_32.inc
includelib \Masm64\Lib\ws2_32.lib
include \Masm64\Include\wsnmp32.inc
includelib \Masm64\Lib\wsnmp32.lib
include \Masm64\Include\wsock32.inc
includelib \Masm64\Lib\wsock32.lib
include \Masm64\Include\wtsapi32.inc
includelib \Masm64\Lib\wtsapi32.lib
include \Masm64\Include\xactsrv.inc
includelib \Masm64\Lib\xactsrv.lib
